"use client";

import { FormEvent, useEffect, useState } from "react";

type Department = { id: string; name: string };
type Employee = { id: string; name: string; email: string; isActive: boolean; presenceStatus: string; departments: { department: Department }[] };
const presence: Record<string, string> = { AVAILABLE: "Available now", AWAY: "Away for now", DO_NOT_DISTURB: "Do not disturb", BE_RIGHT_BACK: "Be right back", OFFLINE: "Offline" };

export default function EmployeesPage() {
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [departments, setDepartments] = useState<Department[]>([]);
  const [selectedId, setSelectedId] = useState("");
  const [message, setMessage] = useState("");
  const [form, setForm] = useState({ name: "", email: "", password: "", departmentIds: [] as string[] });
  async function load() { const [employeeResponse, departmentResponse] = await Promise.all([fetch("/api/employees", { cache: "no-store" }), fetch("/api/departments")]); const employeeData = await employeeResponse.json(); const departmentData = await departmentResponse.json(); setEmployees(employeeData.employees ?? []); setDepartments(departmentData.departments ?? []); }
  useEffect(() => { load(); }, []);
  function toggleDepartment(id: string) { setForm({ ...form, departmentIds: form.departmentIds.includes(id) ? form.departmentIds.filter((value) => value !== id) : [...form.departmentIds, id] }); }
  async function createEmployee(event: FormEvent) { event.preventDefault(); setMessage(""); const response = await fetch("/api/employees", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); setMessage(response.ok ? `Created ${data.employee.name}'s account.` : data.error); if (response.ok) { setForm({ name: "", email: "", password: "", departmentIds: [] }); load(); } }
  async function setActive(id: string, isActive: boolean) { const response = await fetch(`/api/employees/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ isActive }) }); if (response.ok) load(); }
  const selected = employees.find((employee) => employee.id === selectedId);
  return <main className="form-page"><a className="back-link" href="/admin/dashboard">← Admin overview</a><div className="employee-columns"><section className="employee-review"><div className="form-header"><p className="eyebrow">PEOPLE & ACCESS</p><h1>Employees</h1><p>Review team access, departments, and current availability.</p></div><div className="employee-list">{employees.length === 0 ? <div className="viewer-empty">No employees created yet.</div> : employees.map((employee) => <button className={`employee-row ${selectedId === employee.id ? "selected" : ""}`} key={employee.id} onClick={() => setSelectedId(employee.id)}><span className={`presence-dot ${employee.presenceStatus.toLowerCase()}`} /><span className="employee-row-copy"><strong>{employee.name}</strong><small>{employee.email}</small></span><span className="employee-row-status">{presence[employee.presenceStatus]}<br /><i>{employee.isActive ? "Active" : "Disabled"}</i></span></button>)}</div>{selected && <div className="employee-detail"><p className="eyebrow">SELECTED EMPLOYEE</p><h2>{selected.name}</h2><p>{selected.email}</p><div className="detail-departments">{selected.departments.map(({ department }) => <span key={department.id}>{department.name}</span>)}</div><button className="secondary-button" onClick={() => setActive(selected.id, !selected.isActive)}>{selected.isActive ? "Disable account" : "Enable account"}</button></div>}</section><section className="employee-create"><div className="form-header"><p className="eyebrow">NEW ACCOUNT</p><h2>Add an employee</h2><p>Only administrators can create IT accounts.</p></div><form className="control-form" onSubmit={createEmployee}><label>Full name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Employee name" required /></label><label>Work email<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="name@shis.edu.in" required /></label><label>Temporary password<input type="password" minLength={8} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="At least 8 characters" required /></label><fieldset><legend>Department access</legend>{departments.map((department) => <label className="check-row" key={department.id}><input type="checkbox" checked={form.departmentIds.includes(department.id)} onChange={() => toggleDepartment(department.id)} />{department.name}</label>)}</fieldset>{message && <p className={message.startsWith("Created") ? "success-message" : "form-error"}>{message}</p>}<button className="primary-button" disabled={!form.departmentIds.length}>Create account <span>↗</span></button></form></section></div></main>;
}
