"use client";
import { useEffect, useMemo, useState } from "react";

type Employee = { id: string; name: string; email: string; presenceStatus?: string };
type Task = { id: string; title: string; description: string; priority: string; status: string; progressPercentage: number; dueDate: string | null; assignedTo: { id: string; name: string }; department: { name: string }; comments: { id: string; comment: string; createdAt: string; user: { name: string } }[] };
const presenceLabels: Record<string, string> = { AVAILABLE: "Available now", AWAY: "Away for now", DO_NOT_DISTURB: "Do not disturb", BE_RIGHT_BACK: "Be right back", OFFLINE: "Offline" };

export default function EmployeeTaskViewer() {
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [selectedId, setSelectedId] = useState("");
  const selectedTasks = useMemo(() => selectedId ? tasks.filter((task) => task.assignedTo.id === selectedId) : [], [selectedId, tasks]);
  const selectedEmployee = employees.find((employee) => employee.id === selectedId);
  useEffect(() => { Promise.all([fetch("/api/employees"), fetch("/api/tasks")]).then(async ([employeeResponse, taskResponse]) => { const employeeData = await employeeResponse.json(); const taskData = await taskResponse.json(); setEmployees(employeeData.employees ?? []); setTasks(taskData.tasks ?? []); }); }, []);
  return <section className="employee-task-section"><div className="section-heading"><div><p className="eyebrow">INDIVIDUAL WORKLOAD</p><h2>Review employee tasks</h2></div><label className="employee-picker">Select employee<select value={selectedId} onChange={(event) => setSelectedId(event.target.value)}><option value="">Choose a team member</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.name} · {presenceLabels[employee.presenceStatus ?? "AVAILABLE"]}</option>)}</select></label></div>{selectedEmployee && <div className="selected-presence"><span className={`presence-dot ${(selectedEmployee.presenceStatus ?? "AVAILABLE").toLowerCase()}`} />{selectedEmployee.name} is <strong>{presenceLabels[selectedEmployee.presenceStatus ?? "AVAILABLE"]}</strong></div>}{!selectedId ? <div className="viewer-empty">Select an employee to see assigned tasks, progress, updates, and availability.</div> : <div className="admin-task-list">{selectedTasks.length === 0 ? <div className="viewer-empty">No tasks assigned to this employee yet.</div> : selectedTasks.map((task) => <article className="admin-task-card" key={task.id}><div className="admin-task-heading"><div><p className="eyebrow">{task.department.name}</p><h3>{task.title}</h3></div><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span></div><p className="admin-task-description">{task.description || "No description provided."}</p><div className="admin-task-meta"><span className="status-pill">{task.status.replace("_", " ")}</span><span>{task.progressPercentage}% complete</span><span>{task.dueDate ? new Date(task.dueDate).toLocaleDateString("en-GB") : "No deadline"}</span></div><div className="progress-track"><span style={{ width: `${task.progressPercentage}%` }} /></div><div className="admin-comments"><strong>Progress updates</strong>{task.comments.length === 0 ? <p className="no-comments">No comments yet.</p> : task.comments.slice(0, 4).map((comment) => <p className="admin-comment" key={comment.id}><b>{comment.user.name}</b><span>{comment.comment}</span><small>{new Date(comment.createdAt).toLocaleDateString("en-GB")}</small></p>)}</div></article>)}</div>}</section>;
}
