import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import LiveClock from "@/components/live-clock";
import ProfileMenu from "@/components/profile-menu";
import { getGreeting } from "@/lib/greeting";

export default async function AdminDashboardPage() {
  const user = await getCurrentUser();
  if (!user) redirect("/login");
  if (user.role !== "ADMIN") redirect("/dashboard");
  const [employeeCount, tasks, departments] = await Promise.all([prisma.user.count({ where: { role: "EMPLOYEE", isActive: true } }), prisma.task.findMany({ select: { status: true } }), prisma.department.findMany({ include: { _count: { select: { users: true, tasks: true } } }, orderBy: { name: "asc" } })]);
  const completed = tasks.filter((task) => task.status === "COMPLETED").length;
  return <main className="workspace"><aside className="sidebar"><div className="side-brand">SHIS<span>•</span></div><p className="side-label">ADMIN CONSOLE</p><nav><a className="active" href="/admin/dashboard">◈ <span>Overview</span></a><a href="/admin/tasks">□ <span>All tasks</span></a><a href="/admin/employees">♙ <span>Employees</span></a><a href="/chat">◌ <span>Team chat</span></a></nav><div className="side-bottom"><ProfileMenu initial={user.name} userId={user.id} initialStatus={user.presenceStatus} /></div></aside><section className="workspace-main"><header className="topbar"><span>IT DEPARTMENT / ADMIN OVERVIEW</span><div className="topbar-actions"><LiveClock /><button className="icon-button" aria-label="Notifications">♢</button><ProfileMenu initial={user.name} userId={user.id} initialStatus={user.presenceStatus} compact /></div></header><div className="page-content"><div className="welcome"><p className="eyebrow">ADMIN OVERVIEW</p><h1>{getGreeting()}, {user.name.split(" ")[1] ?? "Admin"}.</h1><p>Here is the department-wide pulse for today.</p></div><div className="stat-grid"><div className="stat-card dark"><span>Active employees</span><strong>{employeeCount}</strong><small>ON THE TEAM</small></div><div className="stat-card"><span>Total tasks</span><strong>{tasks.length}</strong><small>ALL STATUSES</small></div><div className="stat-card"><span>Completed</span><strong>{completed}</strong><small>ALL TIME</small></div><div className="stat-card accent"><span>Completion rate</span><strong>{tasks.length ? Math.round(completed / tasks.length * 100) : 0}<small>%</small></strong><small>OVERALL PROGRESS</small></div></div><section className="content-section"><div className="section-heading"><div><p className="eyebrow">FIVE FUNCTIONAL AREAS</p><h2>Department overview</h2></div><a href="/admin/tasks">Review tasks ↗</a></div><div className="department-grid">{departments.map((department) => <div className="department-card" key={department.id}><span className="dept-dot"/><strong>{department.name}</strong><small>{department._count.users} members <i>•</i> {department._count.tasks} tasks</small><div className="progress-line"><span style={{ width: `${department._count.tasks ? 58 : 0}%` }} /></div></div>)}</div></section><footer className="product-credit">Product Designed by Sanchit</footer></div></section></main>;
}
